### ISSUE TITLE
Final Data Products

### ISSUE THREAD

**Issue by veerupandey** [TRIUMF-Capstone2022/richai#36]
Please review the repository and report any errors/suggestions here.

Remaining tasks:

- [x] Add sample data generation script and update in README.md accordingly
- [x] Test model run end to end and save results to `fastscratch`
- [x] Unit tests
- [x] Add report generation once scripts gets executed.  Reports on validation results and test results
- [x] Final docs in repo

**Comment by nicovandenhooff** [comment]
Nico to:
- [ ] Review docstrings
- [ ] Review readme
- [ ] Deploy jupyter book

**Comment by nicovandenhooff** [comment]
- [ ] Make a GitHub release once everything is final.
